fixed error message

diff --git a/.github/workflows/alpha.yml b/.github/workflows/alpha.yml
--- a/.github/workflows/alpha.yml
+++ b/.github/workflows/alpha.yml
@@ -43,3 +43,45 @@ jobs:
         with:
           name: playwright-report
           path: webui/playwright-report
+  publish-report:
+    name: Publish Playwright Report
+    if: "success() || needs.test.result == 'failure'"
+    needs: [release]
+    runs-on: ubuntu-latest
+    env:
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}
+    steps:
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v2dww
+        with:
+          ref: gh-pages
+      - name: Set Git User
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      - name: Download Report
+        uses: actions/download-artifact@v2
+        with:
+          name: playwright-report
+          path: ${{ env.HTML_REPORT_URL_PATH }}
+      - name: Push HTML Report
+        timeout-minutes: 3
+        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+        # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+          
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+          
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
